build_binary:
    image: "golang"
    tags:
        - docker
    stage: build

    before_script:
        - "ln -s $(realpath ./backend-go) /go/src/pixelflut"
    script:
        - "go get pixelflut"
        - "go build pixelflut"
    artifacts:
        expire_in: "1 week"
        paths:
            - "pixelflut"

deploy:
    tags:
        - host
    stage: deploy
    only:
        - master@ftsell/pixelflut
        - web
    
    variables:
        target: "/opt/pixelflut"
        service: "pixelflut.service"

    script:
        - "rsync -r pixelflut $target/"
        - "chgrp pixelflut $target/pixelflut"
        - "sudo /bin/systemctl restart $service"
