[package]
name = "pixelflut"
version = "0.3.0"
authors = ["Finn Sell <dev@finn-thorben.me>"]
edition = "2018"

[dependencies]
websocket = "^0.22.1"
argparse = "^0.2.2"
tokio = "^0.1.14"
futures = "^0.1.25"
hex = "^0.3.2"
base64 = "^0.10.1"
