[package]
name = "pixelflut"
version = "0.1.0"
publish = false
authors = ["Finn-Thorben Sell <dev@finn-thorben.me>"]
edition = "2018"
description = "pixel drawing game for programmers inspired by reddits r/place"
documentation = "https://docs.rs/pixelflut"
readme = "README.md"
repository = "https://github.com/ftsell/pixelflut.git"
license = "MIT"
keywords = ["pixelflut"]
categories = ["command-line-utilities", "games"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
cli = ["clap", "pretty_env_logger"]
gui = ["gtk", "relm4", "relm4-macros", "relm4-components", "pretty_env_logger"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "pixelflut"
path = "src/main.rs"
required-features = ["cli"]

[dependencies]
anyhow = "^1"
base64 = "^0.13"
byteorder = "^1"
bytes = "^1"
clap = { version = "^2", optional = true }
futures-util = "^0.3"
lazy_static = "^1"
log = "^0.4"
nom = "^6"
pretty_env_logger = { version = "^0.4", optional = true }
regex = "^1"
thiserror = "^1"
tokio = { version = "^1", features = ["full"] }
tokio-tungstenite = "^0.13"
gtk = { package = "gtk4", version = "^0.3", features = ["v4_4", "v4_2"], optional = true }
relm4 = { git = "https://github.com/AaronErhardt/relm4.git", features = ["tokio-rt"], optional = true }
relm4-macros = { git = "https://github.com/AaronErhardt/relm4.git", optional = true }
relm4-components = { git = "https://github.com/AaronErhardt/relm4.git", optional = true }

[dev-dependencies]
quickcheck = "0.9.*"
tempfile = "3.*"
