[package]
name = "pixelflut"
version = "0.0.0"
publish = false
authors = ["Finn-Thorben Sell <dev@finn-thorben.me>"]
edition = "2018"
description = "Pixel drawing game for programmers inspired by reddits r/place "
documentation = "https://docs.rs/pixelflut"
readme = "README.md"
repository = "https://github.com/ftsell/pixelflut.git"
license = "MIT"
keywords = ["pixelflut"]
categories = ["command-line-utilities", "games"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[[bin]]
name = "pixelflut_server"

[[bin]]
name = "pixelflut_client"

[dependencies]
#actix = "0.10.*"
#actix-rt = "1.1.*"
#actix-server = "1.*"
tokio = { version = "0.3.*", features = ["full"] }
derive_more = "0.99.*"
bytes = "0.6.*"
nom = "6.*"

[dev-dependencies]
quickcheck = "0.9.*"
