[package]
name = "pixelflut"
version = "0.0.0"
publish = false
authors = ["Finn-Thorben Sell <dev@finn-thorben.me>"]
edition = "2018"
description = "Pixel drawing game for programmers inspired by reddits r/place "
documentation = "https://docs.rs/pixelflut"
readme = "README.md"
repository = "https://github.com/ftsell/pixelflut.git"
license = "MIT"
keywords = ["pixelflut"]
categories = ["command-line-utilities", "games"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
log-impl = ["pretty_env_logger"]

[lib]

[[bin]]
name = "pixelflut_server"
required-features = ["default", "log-impl"]

[[bin]]
name = "pixelflut_client"
required-features = ["default", "log-impl"]

[dependencies]
#actix = "0.10.*"
#actix-rt = "1.1.*"
#actix-server = "1.*"
tokio = { version = "0.3.*", features = ["full"] }
derive_more = "0.99.*"
bytes = "0.6.*"
nom = "6.*"
lazy_static = "1.*"
log = "0.4.*"
pretty_env_logger = { version = "0.4.*", optional = true }
gettext = "0.4.*"
gettext-utils = "0.1.*"
gettext-macros = "0.6.*"

[dev-dependencies]
quickcheck = "0.9.*"
